### ISSUE TITLE
Help with Creating Egocentric Coordinates

### ISSUE THREAD

**Issue by pshonma** [LINCellularNeuroscience/VAME#15]
Hello, 

I am currently trying to use DeepLabCut tracking of mice in an open field arena to implement VAME. I have finished analyzing the Open Field videos using DeepLabCut, but I am having trouble transforming the resulting coordinates into egocentric coordinates. Does anyone have experience in performing this transformation or have any tips for going about this?

Also, I tried using the sample code from the README to convert our csv to np array, but I receive an indexerror (see attached picture) when trying to create a training dataset. Is related to not having egocentric coordinates?
<img width="681" alt="VAME-error" src="https://user-images.githubusercontent.com/58087310/89822231-b6b6b200-db04-11ea-975d-3672b656e7bf.png">

Thanks,
Patrick

**Comment by pavolbauer** [comment]
Dear Patrick,
We are working on a general purpose script for alignment to egocentric coordinates which will soon be released with the next update of VAME.
Best,
Pavol

**Comment by alexcwsmith** [comment]
Hey Pavol,
I am not completely clear how exactly to egocentrically align body parts. I am wondering if you happen to have time would you take a look at the function I have written here and let me know if this is in line with how you do it?

https://github.com/alexcwsmith/VAME/blob/master/vame/custom/helperFunctions.py

Thanks,
Alex

**Comment by KonradDanielewski** [comment]
Hi @alexcwsmith ,

where you able to solve this problem? I have the same issue with my egocentric allignment.

**Comment by KLuxem** [comment]
Hey everyone!

I'm happy to tell you that we just uploaded an alignment script in our [example ](https://github.com/LINCellularNeuroscience/VAME/blob/master/examples/align_demo.py) folder.

The script is quite long, however, most of you can focus on the lines 274-281. Here, you have to specify your VAME directory path and the video filename. The variables `file_format` and `crop_size` are only needed when you also want to align the actual video, otherwise leave them in their default setting.

In line 280, the function call
`egocentric_time_series = align_demo(path_to_file, filename, file_format, crop_size, use_video=False, check_video=False)`
will now automatically align your pose estimation .csv file into an egocentric time series as NumPy array which will be saved into
your `YOUR_VAME_PROJECT/data/filename/` directory in line 281.

Note that, if you don't want to align the actual video frames set `use_video=False` (which is already the case by default). 
However, if you use your video you have the option to set `check_video=True`, which will then play the video afterwards. We used this as a sanity check that everything is working. 

Moreover, the script will interpolate through missing points. We automatically set the x,y-coordinate of your marker to NaN if the accuracy of the pose estimation is lower then 80% (line 127). In our update we will incorporate this as a free parameter and also try to let you decide how you want to interpolate between missing points. 

We hope that this script will help you and allow more people to use VAME. If you find any bugs, please report them here. We are still working towards our next release of VAME with some more functionality and bug fixes. 

Cheers and happy aligning,
Kevin

**Comment by alexcwsmith** [comment]
Hey Kevin,
Thanks! I'm trying this, but when I run align_demo the process starts and runs to 10%, then I get a recursion error:

```
RecursionError: maximum recursion depth exceeded while calling a Python object
```

If I increase the system recursion limit with:
```
import sys
sys.setrecursionlimit(1000000)
```

Then the kernel just dies rather than giving me an error. Setting the limit to 10000 (default is 3000) produces the same error, still at 10% completion.

Any ideas on this? I can't see where the recursion is happening in your code, it may be deeper within the Pandas code? I'm not positive whether that recursion limit would need to be set within a Pandas function or whether me setting the recursion limit should apply to functions in imported packages as well. If you can let me know where to look for anything with deep recursion that may be happening I can probably fix this with threading.

Thanks!
Alex

**Comment by KLuxem** [comment]
Hi Alex,

thank you for reporting this bug. I tested it a little more and run into the same problem. However, we found a quick fix and it should run smoothly now. If not, please let us know. 

Moreover, something I forgot to mention in my previous answer is that you also have to determine two reference points. For example, if you want to align a mouse image, then these would be most likely the snout and tail of the mouse. This is defined in lines 295-302. Make sure that you specify `pose_ref_index` and `pose_flip_ref` with the right coordinates, e.g. snout and tail. 

I hope it works for you now and you can start quantifying your behavioral videos :) 

Cheers,
Kevin

**Comment by alexcwsmith** [comment]
Great, thanks, seems to be running smoothly now! Seems to have a significant speed increase as well (from ~300 to 400 it/s on a 300x300 crop frame), so that's a nice perk of the bug fix.
