### ISSUE TITLE
ValueError during behavior segmentation

### ISSUE THREAD

**Issue by KonradDanielewski** [LINCellularNeuroscience/VAME#20]
Hi,

I'm testing vame for some OF videos I tracked with DLC but when I'm calling `vame.behavior_segmentation(config, model_name='VAME', cluster_method='kmeans', n_cluster=[30])` I get:

![image](https://user-images.githubusercontent.com/54865575/100453418-286a3a00-30bb-11eb-8d7b-7a349ceb2d67.png)

Any idea what might be causing the issue?

**Comment by onurserce** [comment]
I am getting the same error at the same step. Only difference is the array size:

`ValueError: cannot reshape array of size 196 into shape (1,15,14)`

Any help/insights is appreciated.

**Comment by KLuxem** [comment]
Hi,

it seems to be a problem with the `np.reshape()` command in line 141. Did you change anything in your _config.yaml_ after training the network? Especially,
- **num_features**
- **time_window**

The problem is, that `data`, which gets computed in line 140, is in a different shape then expected. If there was no changing of your _config.yaml_, it would be nice if you can check by printing the shape of `data` via `print(data.shape)` to get a further understanding of the problem.

**Comment by onurserce** [comment]
No, absolutely nothing was changed after the training. However, it seems to work fine if I change the time_window parameter from 15 to 14 now.

**Comment by KLuxem** [comment]
Hmm thats interesting. Maybe it has something to do with the odd number of your time_window parameter, I used so far only even numbers. I will definetely look into that and try to fix this bug within our next release. Thank you for your help!

**Comment by onurserce** [comment]
Thank you for the great package!

I have the same impression as you, I believe dividing an odd number by two and then converting this to integer creates the issue since the result is not the half of the time_window parameter and causes numpy to complain. I was just wondering whether there's any disadvantage to increasing or decreasing the time_window parameter by 1 frame?

**Comment by KLuxem** [comment]
Yes exactly. 

You basically don't use the last GRU cell in this setup, but as the parameter of all the other cells are fixed I don't think there is a big problem. However, if you want to use your full time window, maybe you can change `data = X[:,idx-window_start:idx+window_start]` to `data = X[:,idx-window_start:idx+window_start+1]` in the segmentation script. I did not test it but this should fix the problem.

**Comment by KonradDanielewski** [comment]
As it was an issue with an odd number and everything works now, I close this issue. Thank you for help!
