### ISSUE TITLE
RuntimeError: input.size(-1) must be equal to input_size. Expected 12, got 18

### ISSUE THREAD

**Issue by tburnett108** [LINCellularNeuroscience/VAME#27]
Hi, I've been able to run VAME's csv_to_numpy and align_demo.py functions, followed by vame.create_trainset(config). 

Lenght of train data: 9472
Lenght of test data: 2367

but when running 

vame.rnn_model(config, model_name='VAME', pretrained_weights=False, 
     pretrained_model=None) 

I received the above RuntimeError. Is there a solution for this?

**Comment by pavolbauer** [comment]
Hi, try to set the num_features in your config.yaml to 18 as you might be using 18 input dimensions.

**Comment by tburnett108** [comment]
Worked like a charm!
Now experiencing a minor(?) error at behavior quantification:

```
In [8]: vame.behavior_quantification(config, model_name='VAME', cluster_method='kmeans', n_cluster=30)
C:\Users\thomas\.conda\envs\VAME\lib\site-packages\vame-0.1-py3.7.egg\vame\analysis\behavior_structure.py:56: RuntimeWarning: invalid value encountered in true_divide
```
Do you know how to fix this? Thanks.

**Comment by KLuxem** [comment]
Perfect! 

This error happens due to an invalid division like dividing through zero. It might be that in your data not all 30 cluster where detected for all animals and could be a hint that you might wanna reduce the number of cluster for now. 
However, this is something we want to address in our upcoming version of VAME.

**Comment by tburnett108** [comment]
This did the trick! I tried 5 clusters, and several npy files were output. thank you!
