### ISSUE TITLE
I have a few question

### ISSUE THREAD

**Issue by rim-yu** [LINCellularNeuroscience/VAME#30]
Hello. I am RIM-YU. I have a few question. 

1) Is it correct to use .csv file obtained through **deeplabcut.analyze_videos(config_path, ['fullpath/analysis/project/videos/reachingvideo1.avi'], save_as_csv=True)** in VAME algorithm?

2) Approximately how many data in .csv file is optimal for the algorithm?

Thank you.

**Comment by KLuxem** [comment]
Hello Rim-Yu,

1. This is correct, but if your data is not by design egocentrically aligned (e.g. treadmill experiment where the animal is head-fixes) you need to run first our alignment [script](https://github.com/LINCellularNeuroscience/VAME/blob/master/examples/align_demo.py) after you initialised a new vame project.

2. As vame is a generative model parameterized by neural networks it is recommended to have a big training dataset. We used in our paper roughly 1.3 million datapoints. But you can of course try with less and might end up with good results. 

Cheers,
Kevin

**Comment by rim-yu** [comment]
Thanks!
