### ISSUE TITLE
Motifs are not well distinguished

### ISSUE THREAD

**Issue by outlace** [LINCellularNeuroscience/VAME#82]
This is probably not an issue with VAME itself but just need some guidance on the parameters most likely.

```
n_clusters: 30
time_window: 60
```

I have 6 videos of mice in a chamber (top view) just exploring the environment. I have gone through the VAME steps and everything "works" (no errors) although after training the model to convergence the test loss looks odd, it doesn't consistently decrease.

![image](https://user-images.githubusercontent.com/3196399/168677323-6b8dedeb-551a-47d5-aceb-b7fb92ef68a9.png)
When I manually inspect the motif videos I cannot discern that is has learned anything. Each motif video looks like random clips from the videos without any clear behavior patterns.

**Comment by JoTylerG** [comment]
I am having a similar issue, any luck resolving?

**Comment by outlace** [comment]
> I am having a similar issue, any luck resolving?

No luck. We’re just using B-SOID now.

**Comment by pavolbauer** [comment]
Dear outlace,

Sorry that VAME didnt work you so well. We recommend strongly using the bottom view for successful VAME analysis. Alternatively, you can add the velocity or acceleration of the mouse/individual marker points as an additional signal to your behavioral input time series. 

Furthermore, try to set kmeans_lambda to 0 in your config.yaml. Otherwise the learning curves look well, so we recommend to enhance your dataset first, before training a model anew. 

Best
Pavol and Kevin
